"""Agent execution engine — runs agents through their full lifecycle.

This orchestrates the actual execution of each agent:
1. PLAN: Agent uses LLM to decompose its goal into sub-tasks
2. EXECUTE: Run tools, analyze outputs, spawn children
3. AGGREGATE: Collect child results and combine findings
4. REFLECT: Analyze what worked and update strategy
5. REPORT: Produce final result

Each step involves LLM calls with optimized prompts
containing KB context, experience, and hierarchy info.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import structlog

from recursec.agents.recursive_agent_core import (
    AgentRole,
    RecursiveAgent,
    RecursiveAgentManager,
    ROLE_CONFIG,
)

logger = structlog.get_logger()


class ExecutionPhase(str, Enum):
    INIT = "init"
    PLAN = "plan"
    SELECT_TOOLS = "select_tools"
    EXECUTE_TOOLS = "execute_tools"
    ANALYZE_OUTPUT = "analyze_output"
    SPAWN_CHILDREN = "spawn_children"
    WAIT_CHILDREN = "wait_children"
    AGGREGATE = "aggregate"
    VALIDATE = "validate"
    REFLECT = "reflect"
    REPORT = "report"
    DONE = "done"


# Valid phase transitions
PHASE_TRANSITIONS: dict[ExecutionPhase, list[ExecutionPhase]] = {
    ExecutionPhase.INIT: [ExecutionPhase.PLAN],
    ExecutionPhase.PLAN: [ExecutionPhase.SELECT_TOOLS, ExecutionPhase.SPAWN_CHILDREN],
    ExecutionPhase.SELECT_TOOLS: [ExecutionPhase.EXECUTE_TOOLS],
    ExecutionPhase.EXECUTE_TOOLS: [ExecutionPhase.ANALYZE_OUTPUT, ExecutionPhase.SELECT_TOOLS],
    ExecutionPhase.ANALYZE_OUTPUT: [ExecutionPhase.SPAWN_CHILDREN, ExecutionPhase.VALIDATE, ExecutionPhase.SELECT_TOOLS, ExecutionPhase.REPORT],
    ExecutionPhase.SPAWN_CHILDREN: [ExecutionPhase.WAIT_CHILDREN],
    ExecutionPhase.WAIT_CHILDREN: [ExecutionPhase.AGGREGATE],
    ExecutionPhase.AGGREGATE: [ExecutionPhase.VALIDATE, ExecutionPhase.REPORT],
    ExecutionPhase.VALIDATE: [ExecutionPhase.REFLECT],
    ExecutionPhase.REFLECT: [ExecutionPhase.REPORT],
    ExecutionPhase.REPORT: [ExecutionPhase.DONE],
}


@dataclass
class ExecutionStep:
    """A single step in the execution pipeline."""
    step_id: int = 0
    phase: ExecutionPhase = ExecutionPhase.INIT
    action: str = ""
    input_data: dict[str, Any] = field(default_factory=dict)
    output_data: dict[str, Any] = field(default_factory=dict)
    model_used: str = ""
    tokens_used: int = 0
    duration_ms: float = 0.0
    success: bool = True
    error: str = ""
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        return {
            "step": self.step_id,
            "phase": self.phase.value[:10],
            "action": self.action[:20],
            "ok": self.success,
            "tokens": self.tokens_used,
            "ms": f"{self.duration_ms:.0f}",
        }


@dataclass
class ExecutionPlan:
    """Plan generated by the planner LLM for an agent's goal."""
    agent_id: str = ""
    goal: str = ""
    sub_tasks: list[dict[str, Any]] = field(default_factory=list)
    tools_needed: list[str] = field(default_factory=list)
    children_needed: list[dict[str, str]] = field(default_factory=list)
    estimated_steps: int = 10
    strategy: str = "breadth_first"

    def to_dict(self) -> dict[str, Any]:
        return {
            "goal": self.goal[:25],
            "sub_tasks": len(self.sub_tasks),
            "tools": len(self.tools_needed),
            "children": len(self.children_needed),
            "strategy": self.strategy[:15],
        }


# Planning prompt templates per role
PLAN_PROMPTS: dict[AgentRole, str] = {
    AgentRole.COORDINATOR: """You are a security assessment coordinator. Your goal: {goal}
Target: {target}

Plan the assessment by decomposing into specialized sub-tasks.
For each sub-task, specify:
- Description
- Recommended agent role (recon, scanner, exploit, code_audit, web, network, cloud, osint)
- Priority (1-10)
- Dependencies (which sub-tasks must complete first)

Available information from parent: {parent_context}

Output a structured plan.""",

    AgentRole.RECON: """You are a reconnaissance specialist. Your goal: {goal}
Target: {target}

Plan your recon approach:
1. What tools to run (from: {tools})
2. What order to run them
3. What findings would trigger deeper investigation
4. When to spawn OSINT sub-agent

Parent findings: {parent_findings}""",

    AgentRole.SCANNER: """You are a vulnerability scanner. Your goal: {goal}
Target: {target}

Plan your scanning approach:
1. Which scanners to use (from: {tools})
2. Scan configurations and intensity levels
3. How to prioritize scan results
4. When to spawn validator for confirmation

Recon data available: {parent_findings}""",

    AgentRole.WEB: """You are a web application security tester. Your goal: {goal}
Target: {target}

Plan your web testing:
1. Discovery: crawl, dir brute-force, API endpoint enumeration
2. Testing: injection, auth, IDOR, SSRF, XSS, CSRF
3. Tool sequence from: {tools}
4. Manual test cases to try
5. When to spawn validator

Recon data: {parent_findings}""",

    AgentRole.EXPLOIT: """You are an exploitation specialist. Your goal: {goal}
Target: {target}

Plan your exploitation:
1. Which vulnerabilities to attempt (from scan data)
2. Exploitation tools/techniques
3. Post-exploitation goals
4. Evidence collection approach

Vulnerability data: {parent_findings}""",

    AgentRole.CODE_AUDIT: """You are a code auditor. Your goal: {goal}
Target: {target}

Plan your code review:
1. Static analysis tools to run: {tools}
2. Manual review focus areas
3. Vulnerability categories to check
4. How to correlate with dynamic findings

Available context: {parent_findings}""",
}

# Default for roles not listed above
DEFAULT_PLAN_PROMPT = """You are a {role} specialist. Your goal: {goal}
Target: {target}
Tools available: {tools}
Context from parent: {parent_findings}

Create a step-by-step plan to achieve your goal."""


# Tool execution prompt
TOOL_SELECT_PROMPT = """Based on the plan, select the next tool to run.

Current phase: {phase}
Goal: {goal}
Target: {target}
Available tools: {tools}
Already executed: {executed_tools}
Findings so far: {findings_count}

Select the best next tool and provide the exact command to run.
Output format:
TOOL: <tool_name>
COMMAND: <full command>
REASON: <why this tool next>"""


# Analysis prompt
ANALYSIS_PROMPT = """Analyze the following tool output for security findings.

Tool: {tool}
Target: {target}
Raw output:
{output}

For each finding, provide:
- Title
- Severity (critical/high/medium/low/info)
- Description
- Evidence (exact lines from output)
- CWE/CVE if applicable
- Recommended remediation

Be precise. Do not hallucinate findings that aren't in the output."""


class AgentExecutionEngine:
    """Runs agents through their execution lifecycle."""

    def __init__(self, manager: RecursiveAgentManager | None = None) -> None:
        self._manager = manager or RecursiveAgentManager()
        self._execution_steps: dict[str, list[ExecutionStep]] = {}
        self._plans: dict[str, ExecutionPlan] = {}
        self._step_counter = 0
        self._log = logger.bind(component="execution_engine")

    @property
    def manager(self) -> RecursiveAgentManager:
        return self._manager

    def build_plan_prompt(self, agent: RecursiveAgent) -> str:
        """Build the planning prompt for an agent."""
        role_config = ROLE_CONFIG.get(agent.role, {})
        template = PLAN_PROMPTS.get(agent.role, DEFAULT_PLAN_PROMPT)

        parent_findings_text = ""
        if agent.context.parent_findings:
            parent_findings_text = "\n".join(
                f"  - {f.get('title', 'N/A')} [{f.get('severity', 'info')}]"
                for f in agent.context.parent_findings[:10]
            )

        return template.format(
            goal=agent.goal,
            target=agent.context.target,
            tools=", ".join(role_config.get("tools", [])),
            parent_findings=parent_findings_text or "None yet",
            parent_context=str(agent.context.shared_context)[:500],
            role=agent.role.value,
        )

    def build_tool_select_prompt(self, agent: RecursiveAgent, executed: list[str]) -> str:
        """Build prompt for selecting the next tool."""
        role_config = ROLE_CONFIG.get(agent.role, {})
        return TOOL_SELECT_PROMPT.format(
            phase=agent.context.phase,
            goal=agent.goal,
            target=agent.context.target,
            tools=", ".join(role_config.get("tools", [])),
            executed_tools=", ".join(executed) or "none",
            findings_count=len(agent.findings),
        )

    def build_analysis_prompt(self, tool: str, output: str, target: str) -> str:
        """Build prompt for analyzing tool output."""
        return ANALYSIS_PROMPT.format(
            tool=tool,
            target=target,
            output=output[:4000],
        )

    def record_step(
        self,
        agent_id: str,
        phase: ExecutionPhase,
        action: str,
        input_data: dict[str, Any] | None = None,
        output_data: dict[str, Any] | None = None,
        model_used: str = "",
        tokens_used: int = 0,
        success: bool = True,
        error: str = "",
    ) -> ExecutionStep:
        """Record an execution step."""
        self._step_counter += 1
        step = ExecutionStep(
            step_id=self._step_counter,
            phase=phase,
            action=action,
            input_data=input_data or {},
            output_data=output_data or {},
            model_used=model_used,
            tokens_used=tokens_used,
            success=success,
            error=error,
        )

        if agent_id not in self._execution_steps:
            self._execution_steps[agent_id] = []
        self._execution_steps[agent_id].append(step)

        # Update agent budgets
        agent = self._manager._agents.get(agent_id)
        if agent:
            agent.token_budget.consume(input_tokens=tokens_used // 2, output_tokens=tokens_used // 2)
            self._manager.record_action(agent_id, action)

        return step

    def store_plan(self, agent_id: str, plan: ExecutionPlan) -> None:
        """Store the execution plan for an agent."""
        self._plans[agent_id] = plan

    def get_plan(self, agent_id: str) -> ExecutionPlan | None:
        """Get the stored plan for an agent."""
        return self._plans.get(agent_id)

    def check_should_continue(self, agent_id: str) -> tuple[bool, str]:
        """Check if agent should continue executing."""
        agent = self._manager._agents.get(agent_id)
        if not agent:
            return False, "agent_not_found"

        # Budget checks
        if agent.token_budget.exhausted:
            return False, "token_budget_exhausted"
        if agent.step_budget.exhausted:
            return False, "step_budget_exhausted"

        # Convergence check
        if self._manager.check_convergence(agent_id):
            return False, "converged_or_stuck"

        # Time limit (10 min per agent)
        if agent.elapsed_s > 600:
            return False, "timeout"

        return True, "ok"

    def get_execution_trace(self, agent_id: str) -> list[dict[str, Any]]:
        """Get the full execution trace for an agent."""
        steps = self._execution_steps.get(agent_id, [])
        return [s.to_dict() for s in steps]

    def get_stats(self) -> dict[str, Any]:
        total_steps = sum(len(s) for s in self._execution_steps.values())
        total_tokens = sum(
            sum(s.tokens_used for s in steps)
            for steps in self._execution_steps.values()
        )
        return {
            "agents_tracked": len(self._execution_steps),
            "total_steps": total_steps,
            "total_tokens": total_tokens,
            "plans_stored": len(self._plans),
            "manager_stats": self._manager.get_stats(),
        }

    def build_execution_context_prompt(self, agent_id: str) -> str:
        """Build a prompt with the full execution context for an agent."""
        agent = self._manager._agents.get(agent_id)
        if not agent:
            return ""

        lines = []

        # Hierarchy context
        hierarchy = self._manager.build_hierarchy_prompt(agent_id)
        if hierarchy:
            lines.append(hierarchy)

        # Execution trace summary
        steps = self._execution_steps.get(agent_id, [])
        if steps:
            lines.append(f"\n## Execution History ({len(steps)} steps)")
            for step in steps[-5:]:
                status = "OK" if step.success else "FAIL"
                lines.append(f"  [{status}] {step.phase.value}: {step.action[:40]}")

        # Current plan
        plan = self._plans.get(agent_id)
        if plan:
            completed_tasks = sum(1 for t in plan.sub_tasks if t.get("completed"))
            lines.append(f"\n## Plan Progress: {completed_tasks}/{len(plan.sub_tasks)} sub-tasks")

        # Budget status
        should_continue, reason = self.check_should_continue(agent_id)
        if not should_continue:
            lines.append(f"\n⚠ STOPPING: {reason}")

        return "\n".join(lines)
